import { componentRegistry } from '../../.nativecore/core/lazyComponents.js';

export const builtinComponentManifest = [
    ['loading-spinner', './components/loading-spinner.js'],
    ['nc-a', './components/nc-a.js'],
    ['nc-accordion-item', './components/nc-accordion.js'],
    ['nc-accordion', './components/nc-accordion.js'],
    ['nc-alert', './components/nc-alert.js'],
    ['nc-animation', './components/nc-animation.js'],
    ['nc-autocomplete', './components/nc-autocomplete.js'],
    ['nc-avatar', './components/nc-avatar.js'],
    ['nc-avatar-group', './components/nc-avatar-group.js'],
    ['nc-badge', './components/nc-badge.js'],
    ['nc-bottom-nav-item', './components/nc-bottom-nav.js'],
    ['nc-bottom-nav', './components/nc-bottom-nav.js'],
    ['nc-breadcrumb', './components/nc-breadcrumb.js'],
    ['nc-button', './components/nc-button.js'],
    ['nc-card', './components/nc-card.js'],
    ['nc-checkbox', './components/nc-checkbox.js'],
    ['nc-chip', './components/nc-chip.js'],
    ['nc-code', './components/nc-code.js'],
    ['nc-collapsible', './components/nc-collapsible.js'],
    ['nc-color-picker', './components/nc-color-picker.js'],
    ['nc-copy-button', './components/nc-copy-button.js'],
    ['nc-date-picker', './components/nc-date-picker.js'],
    ['nc-div', './components/nc-div.js'],
    ['nc-divider', './components/nc-divider.js'],
    ['nc-drawer', './components/nc-drawer.js'],
    ['nc-dropdown', './components/nc-dropdown.js'],
    ['nc-empty-state', './components/nc-empty-state.js'],
    ['nc-field', './components/nc-form.js'],
    ['nc-file-upload', './components/nc-file-upload.js'],
    ['nc-form', './components/nc-form.js'],
    ['nc-image', './components/nc-image.js'],
    ['nc-input', './components/nc-input.js'],
    ['nc-kbd', './components/nc-kbd.js'],
    ['nc-menu', './components/nc-menu.js'],
    ['nc-menu-item', './components/nc-menu-item.js'],
    ['nc-modal', './components/nc-modal.js'],
    ['nc-nav-item', './components/nc-nav-item.js'],
    ['nc-number-input', './components/nc-number-input.js'],
    ['nc-otp-input', './components/nc-otp-input.js'],
    ['nc-pagination', './components/nc-pagination.js'],
    ['nc-popover', './components/nc-popover.js'],
    ['nc-progress', './components/nc-progress.js'],
    ['nc-progress-circular', './components/nc-progress-circular.js'],
    ['nc-radio', './components/nc-radio.js'],
    ['nc-rating', './components/nc-rating.js'],
    ['nc-rich-text', './components/nc-rich-text.js'],
    ['nc-scroll-top', './components/nc-scroll-top.js'],
    ['nc-select', './components/nc-select.js'],
    ['nc-skeleton', './components/nc-skeleton.js'],
    ['nc-slider', './components/nc-slider.js'],
    ['nc-snackbar', './components/nc-snackbar.js'],
    ['nc-splash', './components/nc-splash.js'],
    ['nc-step', './components/nc-stepper.js'],
    ['nc-stepper', './components/nc-stepper.js'],
    ['nc-switch', './components/nc-switch.js'],
    ['nc-tab-item', './components/nc-tab-item.js'],
    ['nc-table', './components/nc-table.js'],
    ['nc-tabs', './components/nc-tabs.js'],
    ['nc-tag-input', './components/nc-tag-input.js'],
    ['nc-textarea', './components/nc-textarea.js'],
    ['nc-time-picker', './components/nc-time-picker.js'],
    ['nc-timeline-item', './components/nc-timeline.js'],
    ['nc-timeline', './components/nc-timeline.js'],
    ['nc-tooltip', './components/nc-tooltip.js']
] as const;

export function registerBuiltinComponents(): void {
    builtinComponentManifest.forEach(([tagName, modulePath]) => {
        componentRegistry.register(tagName, modulePath);
    });
}

